language: node_js
branches:
  only:
  - hexo #源码分支名称
before_install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install -g hexo-renderer-jade --save
- npm install -g hexo-renderer-stylus --save
before_script:
- git config --global user.name 'dogold'
- git config --global user.email 'ligr1991@gmail.com'
- sed -i'' "s~git@github.com:dogold/dogold.github.io.git~https://${GITHUB_REPO_TOKEN}:x-oauth-basic@github.com/dogold/dogold.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
