language: node_js
branches:
  only:
  - master #源码分支名称
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'yourname'
- git config --global user.email 'youremail'
- sed -i'' "s~git@github.com:dogold/dogold.github.io.git.git~https://${GITHUB_REPO_TOKEN}:x-oauth-basic@github.com/dogold/dogold.github.io.git.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
